### PR TITLE
Remove BOMs from files as it causes issues with utilities like cfformat

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by lmajano** [comment]
but if you remove boms then utf8 will be lost and localized strings won't show, is that the case? @bdw429s

**Comment by elpete** [comment]
Not that I read. It is optional. https://en.m.wikipedia.org/wiki/Byte_order_mark

It is breaking cfformat

**Comment by bdw429s** [comment]
@elpete Isn't this a bug in CFFormat that needs addressed?

**Comment by elpete** [comment]
I brought it up to @jcberquist who pointed out it was a BOM causing the issues. Evidently they cause issues for multiple libraries. He said he was looking in to a fix, but as it is optional and only causing problems, I say we remove them.

**Comment by jcberquist** [comment]
For what it is worth, CFFormat should work with UTF-8 BOMs now. Though the link @elpete provided above indicates a UTF-8 BOM is somewhat unecessary?

> The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use.

**Comment by bdw429s** [comment]
Of course, they're optional, but I think that's beside the point.  BOMs are also extremely common and auto-added by many editors so removing them from a couple files seems like a drop in the bucket when the reality is that any tool dealing with text files should expect and properly handle BOMs.

**Pull request merged**
